### ISSUE TITLE
CP UMAT for ABAQUS that incorporates length scale effects

### ISSUE THREAD

**Issue by leoving** [smrg-uob/Dream3d2Abaqus#2]
the link of https://github.com/smrg-uob/CP UMATs is empty

**Comment by DylanAgius** [comment]
Hi Leoving,

For more information on how to create a UMAT to incorporate the grain size effects, you can look at the following repo: https://github.com/DylanAgius/LengMorph.  In the repo, there are examples of how to apply the size effect developed for classical crystal plasticity approaches as well as links to the appropriate publications detailing the approach.

Regards,

Dylan
